"""Prefix data structures, string unification, and admissibility checks for Wallen's method."""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, List, Tuple, Optional, Dict, Any, Set, Union

if TYPE_CHECKING:
    from logic_prover.constructive.matrix import FormulaTree


@dataclass(frozen=True, slots=True)
class PrefixSymbol:
    """Base class for world prefix symbols in Kripke frames.

    Args:
        name (str): The unique string identifier of the prefix symbol.

    Example:
        >>> from logic_prover.constructive.prefix import PrefixSymbol
        >>> sym = PrefixSymbol(name="w0")
        >>> sym.name
        'w0'
    """

    name: str

    def __str__(self) -> str:
        """Returns the string representation of the prefix symbol.

        Returns:
            str: Symbol name.

        Example:
            >>> from logic_prover.constructive.prefix import PrefixConstant
            >>> str(PrefixConstant(name="c0"))
            'c0'
        """
        return self.name


@dataclass(frozen=True, slots=True)
class PrefixConstant(PrefixSymbol):
    """Static world parameter constant generated by intuitionistic psi-nodes.

    Args:
        name (str): The unique identifier name of the constant.

    Example:
        >>> from logic_prover.constructive.prefix import PrefixConstant
        >>> c = PrefixConstant(name="c1")
        >>> c.name
        'c1'
    """
    pass


@dataclass(frozen=True, slots=True)
class PrefixVariable(PrefixSymbol):
    """Dynamic world variable generated by intuitionistic phi-nodes.

    Args:
        name (str): The unique identifier name of the variable.

    Example:
        >>> from logic_prover.constructive.prefix import PrefixVariable
        >>> v = PrefixVariable(name="V1")
        >>> v.name
        'V1'
    """
    pass


@dataclass(frozen=True)
class Prefix:
    """An immutable sequence of world prefix symbols representing a path in a Kripke frame.

    Args:
        symbols (Tuple[PrefixSymbol, ...], default=()): Tuple of prefix symbols.

    Example:
        >>> from logic_prover.constructive.prefix import Prefix, PrefixConstant, PrefixVariable
        >>> c0 = PrefixConstant("c0")
        >>> v1 = PrefixVariable("V1")
        >>> pre = Prefix((c0, v1))
        >>> len(pre)
        2
        >>> str(pre)
        'c0.V1'
    """

    symbols: Tuple[PrefixSymbol, ...] = field(default_factory=tuple)

    def __post_init__(self) -> None:
        """Ensures symbols are stored as an immutable tuple."""
        if not isinstance(self.symbols, tuple):
            object.__setattr__(self, "symbols", tuple(self.symbols))

    def __len__(self) -> int:
        """Returns the number of prefix symbols.

        Returns:
            int: Prefix length.

        Example:
            >>> from logic_prover.constructive.prefix import Prefix, PrefixConstant
            >>> len(Prefix((PrefixConstant("c0"),)))
            1
        """
        return len(self.symbols)

    def __getitem__(self, idx: Union[int, slice]) -> Union[PrefixSymbol, Prefix]:
        """Indexes or slices the prefix.

        Args:
            idx (Union[int, slice]): Index or slice.

        Returns:
            Union[PrefixSymbol, Prefix]: Symbol at index or sliced Prefix.

        Example:
            >>> from logic_prover.constructive.prefix import Prefix, PrefixConstant
            >>> c0 = PrefixConstant("c0")
            >>> pre = Prefix((c0,))
            >>> pre[0].name
            'c0'
        """
        if isinstance(idx, slice):
            return Prefix(self.symbols[idx])
        return self.symbols[idx]

    def append(self, symbol: PrefixSymbol) -> Prefix:
        """Appends a prefix symbol and returns a new Prefix.

        Args:
            symbol (PrefixSymbol): The symbol to append.

        Returns:
            Prefix: Extended prefix.

        Example:
            >>> from logic_prover.constructive.prefix import Prefix, PrefixConstant
            >>> c0 = PrefixConstant("c0")
            >>> c1 = PrefixConstant("c1")
            >>> p = Prefix((c0,)).append(c1)
            >>> str(p)
            'c0.c1'
        """
        return Prefix(self.symbols + (symbol,))

    def variables(self) -> Set[PrefixVariable]:
        """Returns the set of prefix variables occurring in the prefix.

        Returns:
            Set[PrefixVariable]: All prefix variables in this prefix.

        Example:
            >>> from logic_prover.constructive.prefix import Prefix, PrefixConstant, PrefixVariable
            >>> pre = Prefix((PrefixConstant("c0"), PrefixVariable("V1")))
            >>> len(pre.variables())
            1
        """
        return {s for s in self.symbols if isinstance(s, PrefixVariable)}

    def constants(self) -> Set[PrefixConstant]:
        """Returns the set of prefix constants occurring in the prefix.

        Returns:
            Set[PrefixConstant]: All prefix constants in this prefix.

        Example:
            >>> from logic_prover.constructive.prefix import Prefix, PrefixConstant
            >>> pre = Prefix((PrefixConstant("c0"),))
            >>> len(pre.constants())
            1
        """
        return {s for s in self.symbols if isinstance(s, PrefixConstant)}

    def to_string(self) -> str:
        """Formats the prefix as a dot-separated string.

        Returns:
            str: Dot-separated string of prefix symbols.

        Example:
            >>> from logic_prover.constructive.prefix import Prefix, PrefixConstant, PrefixVariable
            >>> pre = Prefix((PrefixConstant("c0"), PrefixVariable("V1")))
            >>> pre.to_string()
            'c0.V1'
        """
        if not self.symbols:
            return "eps"
        return ".".join(s.name for s in self.symbols)

    def __str__(self) -> str:
        """Returns the string representation of the prefix.

        Returns:
            str: Dot-separated string representation.
        """
        return self.to_string()


@dataclass
class PrefixSubstitution:
    """Mapping from prefix variables to sequences of prefix symbols.

    Args:
        mapping (Optional[Dict[PrefixVariable, Tuple[PrefixSymbol, ...]]], default=None): Variable map.

    Example:
        >>> from logic_prover.constructive.prefix import PrefixSubstitution, PrefixVariable, PrefixConstant
        >>> v = PrefixVariable("V1")
        >>> c = PrefixConstant("c1")
        >>> subst = PrefixSubstitution({v: (c,)})
        >>> subst.get(v)
        (PrefixConstant(name='c1'),)
    """

    mapping: Dict[PrefixVariable, Tuple[PrefixSymbol, ...]] = field(default_factory=dict)

    def copy(self) -> PrefixSubstitution:
        """Creates a deep copy of the substitution.

        Returns:
            PrefixSubstitution: Cloned substitution.

        Example:
            >>> from logic_prover.constructive.prefix import PrefixSubstitution
            >>> s = PrefixSubstitution()
            >>> s_copy = s.copy()
            >>> len(s_copy.mapping)
            0
        """
        return PrefixSubstitution(dict(self.mapping))

    def bind(self, var: PrefixVariable, term: Tuple[PrefixSymbol, ...]) -> PrefixSubstitution:
        """Binds a variable to a term and applies substitution transitively.

        Args:
            var (PrefixVariable): Variable to bind.
            term (Tuple[PrefixSymbol, ...]): Replacement tuple of symbols.

        Returns:
            PrefixSubstitution: New extended substitution.

        Example:
            >>> from logic_prover.constructive.prefix import PrefixSubstitution, PrefixVariable, PrefixConstant
            >>> v = PrefixVariable("V1")
            >>> c = PrefixConstant("c1")
            >>> s = PrefixSubstitution().bind(v, (c,))
            >>> s.get(v)
            (PrefixConstant(name='c1'),)
        """
        new_map: Dict[PrefixVariable, Tuple[PrefixSymbol, ...]] = {}
        for k, v in self.mapping.items():
            new_val: List[PrefixSymbol] = []
            for sym in v:
                if sym == var:
                    new_val.extend(term)
                else:
                    new_val.append(sym)
            new_map[k] = tuple(new_val)
        new_map[var] = term
        return PrefixSubstitution(new_map)

    def get(self, var: PrefixVariable) -> Optional[Tuple[PrefixSymbol, ...]]:
        """Retrieves the bound term for a prefix variable.

        Args:
            var (PrefixVariable): Variable to look up.

        Returns:
            Optional[Tuple[PrefixSymbol, ...]]: Bound term or None.

        Example:
            >>> from logic_prover.constructive.prefix import PrefixSubstitution, PrefixVariable
            >>> v = PrefixVariable("V1")
            >>> s = PrefixSubstitution()
            >>> s.get(v) is None
            True
        """
        return self.mapping.get(var)

    def apply(self, prefix: Prefix) -> Prefix:
        """Applies the substitution fully to a prefix.

        Args:
            prefix (Prefix): Prefix to instantiate.

        Returns:
            Prefix: Instantiated prefix.

        Example:
            >>> from logic_prover.constructive.prefix import PrefixSubstitution, Prefix, PrefixVariable, PrefixConstant
            >>> v = PrefixVariable("V1")
            >>> c0 = PrefixConstant("c0")
            >>> c1 = PrefixConstant("c1")
            >>> s = PrefixSubstitution({v: (c1,)})
            >>> res = s.apply(Prefix((c0, v)))
            >>> str(res)
            'c0.c1'
        """
        res: List[PrefixSymbol] = []
        for sym in prefix.symbols:
            if isinstance(sym, PrefixVariable) and sym in self.mapping:
                res.extend(self.mapping[sym])
            else:
                res.append(sym)
        return Prefix(tuple(res))

    def to_dict(self) -> Dict[str, str]:
        """Serializes the substitution to a string-keyed dictionary.

        Returns:
            Dict[str, str]: Serialized variable-to-string mappings.

        Example:
            >>> from logic_prover.constructive.prefix import PrefixSubstitution, PrefixVariable, PrefixConstant
            >>> s = PrefixSubstitution({PrefixVariable("V1"): (PrefixConstant("c1"),)})
            >>> s.to_dict()
            {'V1': 'c1'}
        """
        return {k.name: ".".join(s.name for s in v) for k, v in self.mapping.items()}


def unify_prefixes(
    p1: Prefix,
    p2: Prefix,
    subst: Optional[PrefixSubstitution] = None,
) -> List[PrefixSubstitution]:
    """Generates all most general intuitionistic T-string prefix substitutions solving p1 = p2.

    Implements string equation solving for S4 / intuitionistic world prefix words
    (Otten & Kreitz 1996; Wallen 1990).

    Args:
        p1 (Prefix): First prefix word.
        p2 (Prefix): Second prefix word.
        subst (Optional[PrefixSubstitution], default=None): Initial prefix substitution.

    Returns:
        List[PrefixSubstitution]: List of viable unifying substitutions.

    Example:
        >>> from logic_prover.constructive.prefix import unify_prefixes, Prefix, PrefixConstant, PrefixVariable
        >>> c0 = PrefixConstant("c0")
        >>> c1 = PrefixConstant("c1")
        >>> v1 = PrefixVariable("V1")
        >>> unifs = unify_prefixes(Prefix((c0, v1)), Prefix((c0, c1)))
        >>> len(unifs)
        1
        >>> unifs[0].get(v1)
        (PrefixConstant(name='c1'),)
    """
    initial_subst = subst.copy() if subst is not None else PrefixSubstitution()

    def _unify_words(
        w1: Tuple[PrefixSymbol, ...],
        w2: Tuple[PrefixSymbol, ...],
        current: PrefixSubstitution,
    ) -> List[PrefixSubstitution]:
        # Strip common prefix constants/variables
        while w1 and w2 and w1[0] == w2[0]:
            w1 = w1[1:]
            w2 = w2[1:]

        # If both words are empty, success
        if not w1 and not w2:
            return [current]

        # If w1 is empty and w2 is not:
        if not w1 and w2:
            s2 = w2[0]
            if isinstance(s2, PrefixVariable):
                bound = current.get(s2)
                if bound is not None:
                    return _unify_words((), bound + w2[1:], current)
                new_sub = current.bind(s2, ())
                tail2 = tuple(sym for s in w2[1:] for sym in (new_sub.get(s) if isinstance(s, PrefixVariable) and new_sub.get(s) is not None else (s,)))
                return _unify_words((), tail2, new_sub)
            return []

        # If w2 is empty and w1 is not:
        if not w2 and w1:
            s1 = w1[0]
            if isinstance(s1, PrefixVariable):
                bound = current.get(s1)
                if bound is not None:
                    return _unify_words(bound + w1[1:], (), current)
                new_sub = current.bind(s1, ())
                tail1 = tuple(sym for s in w1[1:] for sym in (new_sub.get(s) if isinstance(s, PrefixVariable) and new_sub.get(s) is not None else (s,)))
                return _unify_words(tail1, (), new_sub)
            return []

        s1, s2 = w1[0], w2[0]

        # Case 1: Constant vs Constant mismatch
        if isinstance(s1, PrefixConstant) and isinstance(s2, PrefixConstant):
            return []

        results: List[PrefixSubstitution] = []

        # Case 2: Variable on left
        if isinstance(s1, PrefixVariable):
            bound = current.get(s1)
            if bound is not None:
                return _unify_words(bound + w1[1:], w2, current)

            new_sub_empty = current.bind(s1, ())
            tail1_empty = tuple(sym for s in w1[1:] for sym in (new_sub_empty.get(s) if isinstance(s, PrefixVariable) and new_sub_empty.get(s) is not None else (s,)))
            results.extend(_unify_words(tail1_empty, w2, new_sub_empty))

            for split_idx in range(1, len(w2) + 1):
                prefix_slice = w2[:split_idx]
                if s1 in prefix_slice:
                    continue
                new_sub = current.bind(s1, prefix_slice)
                tail1 = w1[1:]
                tail2 = w2[split_idx:]
                new_w1 = tuple(sym for s in tail1 for sym in (new_sub.get(s) if isinstance(s, PrefixVariable) and new_sub.get(s) is not None else (s,)))
                new_w2 = tuple(sym for s in tail2 for sym in (new_sub.get(s) if isinstance(s, PrefixVariable) and new_sub.get(s) is not None else (s,)))
                results.extend(_unify_words(new_w1, new_w2, new_sub))
            return results

        # Case 3: Variable on right
        if isinstance(s2, PrefixVariable):
            bound = current.get(s2)
            if bound is not None:
                return _unify_words(w1, bound + w2[1:], current)

            new_sub_empty = current.bind(s2, ())
            tail2_empty = tuple(sym for s in w2[1:] for sym in (new_sub_empty.get(s) if isinstance(s, PrefixVariable) and new_sub_empty.get(s) is not None else (s,)))
            results.extend(_unify_words(w1, tail2_empty, new_sub_empty))

            for split_idx in range(1, len(w1) + 1):
                prefix_slice = w1[:split_idx]
                if s2 in prefix_slice:
                    continue
                new_sub = current.bind(s2, prefix_slice)
                tail1 = w1[split_idx:]
                tail2 = w2[1:]
                new_w1 = tuple(sym for s in tail1 for sym in (new_sub.get(s) if isinstance(s, PrefixVariable) and new_sub.get(s) is not None else (s,)))
                new_w2 = tuple(sym for s in tail2 for sym in (new_sub.get(s) if isinstance(s, PrefixVariable) and new_sub.get(s) is not None else (s,)))
                results.extend(_unify_words(new_w1, new_w2, new_sub))
            return results

        return []

    inst_p1 = initial_subst.apply(p1).symbols
    inst_p2 = initial_subst.apply(p2).symbols
    return _unify_words(inst_p1, inst_p2, initial_subst)


def is_admissible(tree: FormulaTree, subst: PrefixSubstitution) -> bool:
    """Verifies that the reduction ordering < = (<_0 U <_sigma)+ is strictly acyclic.

    In Wallen's matrix proof method, an intuitionistic substitution sigma is admissible
    if the combination of formula tree ordering <_0 and induced substitution ordering
    <_sigma contains no directed cycles.

    Args:
        tree (FormulaTree): The formula tree defining tree ordering <_0.
        subst (PrefixSubstitution): The candidate prefix substitution.

    Returns:
        bool: True if the combined reduction ordering is acyclic, False otherwise.

    Example:
        >>> from logic_prover.core.ast import PredicateApp, Implies
        >>> from logic_prover.constructive.matrix import FormulaTree
        >>> from logic_prover.constructive.prefix import PrefixSubstitution, is_admissible
        >>> p = PredicateApp(pred="P", arity=0, args=())
        >>> tree = FormulaTree(target=Implies(p, p))
        >>> is_admissible(tree, PrefixSubstitution())
        True
    """
    adj: Dict[PrefixSymbol, Set[PrefixSymbol]] = {}
    for node, targets in tree.tree_order.items():
        adj[node] = set(targets)

    for var, term in subst.mapping.items():
        if var not in adj:
            adj[var] = set()
        for sym in term:
            if sym not in adj:
                adj[sym] = set()
            if sym != var:
                adj[sym].add(var)

    visited: Dict[PrefixSymbol, int] = {node: 0 for node in adj}

    def _has_cycle(u: PrefixSymbol) -> bool:
        visited[u] = 1
        for v in adj.get(u, ()):
            if v not in visited:
                visited[v] = 0
            if visited[v] == 1:
                return True
            if visited[v] == 0 and _has_cycle(v):
                return True
        visited[u] = 2
        return False

    for node in list(adj.keys()):
        if visited[node] == 0:
            if _has_cycle(node):
                return False

    return True


__all__ = [
    "PrefixSymbol",
    "PrefixConstant",
    "PrefixVariable",
    "Prefix",
    "PrefixSubstitution",
    "unify_prefixes",
    "is_admissible",
]
