"""
Group Theory Axioms and Autonomous Deduction Engine
=====================================================
Loads group theory axioms into group.db, uses solver.deducer to autonomously
discover propositions and formal proofs, saves results in group.db, and exports
all verified theorems to group.lean.
"""

from solver.database import TheoryDatabase
from solver.dependencies.first_order_logic import load_first_order_axioms
from solver.deducer import Deducer
from solver.verifier import verify_proof_local
from solver.lean_exporter import export_proof, formula_to_lean
from solver.graph_exporter import export_graph_dot, export_graph_html
from solver.formula import parse_formula

# ---------------------------------------------------------------------------
# Group Theory Axioms Definition
# ---------------------------------------------------------------------------
GROUP_THEORY_AXIOMS = {
    # Associativity: f(f(x, y), z) = f(x, f(y, z))
    "grp_assoc": "f(f(x, y), z) = f(x, f(y, z))",

    # Left Identity: f(e, x) = x
    "grp_id_left": "f(e, x) = x",

    # Right Identity: f(x, e) = x
    "grp_id_right": "f(x, e) = x",

    # Left Inverse: f(inv(x), x) = e
    "grp_inv_left": "f(inv(x), x) = e",

    # Right Inverse: f(x, inv(x)) = e
    "grp_inv_right": "f(x, inv(x)) = e",
}


def init_group_database(db_path="group.db"):
    """Initializes the group theory database with FOL and Group Theory axioms."""
    db = TheoryDatabase(db_path)

    # Load First-Order Logic foundational axioms
    load_first_order_axioms(db)

    # Register Group Theory axioms
    for ax_name, ax_str in GROUP_THEORY_AXIOMS.items():
        db.add_axiom(ax_name, ax_str)

    return db


def discover_group_propositions(db: TheoryDatabase):
    """
    Autonomously discovers propositions in Group Theory using solver.deducer.
    No hardcoded proof steps or target theorems are provided.
    """
    print("\n--- Autonomous Deduction Engine ---")

    # Use forward Deducer engine to derive logical consequences starting from axioms
    deducer = Deducer(db=db, auto_load_axioms=False)

    # Ground terms / properties for group element exploration
    hypotheses = [
        "f(e, a) = a",
        "f(a, inv(a)) = e",
        "f(a, b) = c",
        "f(b, c) = d"
    ]

    consequences = deducer.deduce(
        hypotheses=hypotheses,
        max_formulas=30,
        include_hypotheses=False,
        require_axioms=True,
        target_axiom_prefix="grp_",
        exclude_pure_hypotheses=True
    )

    print(f"Discovered {len(consequences)} autonomous consequences via Deducer:")
    discovered_count = 0

    for i, c in enumerate(consequences, 1):
        thm_name = f"auto_thm_{i}"
        thm_def = {
            'name': thm_name,
            'thesis_str': c.formula_str,
            'hypotheses': hypotheses,
            'steps': c.proof
        }

        # Perform local formal logic verification
        is_valid, err = verify_proof_local(thm_def, db)
        if is_valid:
            try:
                lean_code = export_proof(thm_name, db)
            except Exception:
                lean_code = None

            db.save_theorem(
                name=thm_name,
                thesis_str=c.formula_str,
                hypotheses=hypotheses,
                steps=c.proof,
                lean_code=lean_code,
                is_verified=1
            )
            discovered_count += 1
            print(f"  [{i}] Saved verified theorem '{thm_name}': {c.formula_str} ({c.justification_type})")
        else:
            print(f"  [{i}] Local verification skipped for: {c.formula_str} ({err})")

    print(f"\nSuccessfully discovered and saved {discovered_count} verified theorems into group.db.")


def export_database_to_lean(db: TheoryDatabase, output_lean_file="group.lean"):
    """
    Exports all axioms and autonomously discovered theorems from group.db into a Lean 4 file.
    """
    lines = [
        "-- Group Theory Formalization in Lean 4",
        "-- Autonomously Generated by solver Library",
        "",
        "variable (G : Type)",
        "variable (f : G → G → G)",
        "variable (e : G)",
        "variable (inv : G → G)",
        "",
        "-- Group Theory Axioms"
    ]

    axioms = db.get_all_axioms()
    for name, f_str in axioms.items():
        f_ast = parse_formula(f_str)
        lines.append(f"axiom {name} : {formula_to_lean(f_ast)}")
    lines.append("")

    # Export all verified theorems from group.db
    with db.connection_scope() as conn:
        cursor = conn.execute("SELECT name FROM theorems WHERE is_verified = 1;")
        verified_thm_names = [row[0] for row in cursor.fetchall()]

    lines.append(f"-- Autonomously Discovered Verified Theorems ({len(verified_thm_names)})")
    for name in verified_thm_names:
        try:
            lean_code = export_proof(name, db)
            lines.append(f"-- Proof for {name}")
            lines.append(lean_code)
        except Exception as err:
            lines.append(f"-- Note on {name}: {err}")

    with open(output_lean_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Successfully exported Lean 4 formalization to '{output_lean_file}'.")


def main():
    print("=== Autonomous Group Theory Proposition Discovery ===")
    db_path = "group.db"
    lean_path = "group.lean"
    dot_path = "group_graph.dot"
    html_path = "group_graph.html"

    # Step 1: Initialize Database with Axioms
    db = init_group_database(db_path)
    print(f"Initialized '{db_path}' with {len(db.get_all_axioms())} axioms.")

    # Step 2: Autonomously Discover Group Propositions
    discover_group_propositions(db)

    # Step 3: Export Discovered Results into Lean File
    export_database_to_lean(db, lean_path)

    # Step 4: Export Graph of Results (Axioms and Hypotheses as nodes connected to Results)
    export_graph_dot(db, dot_path)
    export_graph_html(db, html_path)
    print(f"Successfully generated graph visualizations: '{dot_path}' and '{html_path}'.")
    print("Execution complete.")


if __name__ == "__main__":
    main()
