import unittest
import tempfile
import os
from unittest.mock import patch

from solver.formula import (
    Var, Not, Implies, And, Or, Iff,
    Forall, Exists, Equals, Pred
)
from solver.database import TheoryDatabase
from solver.lean_exporter import formula_to_lean, export_proof


class TestFormulaToLean(unittest.TestCase):
    def test_var(self):
        self.assertEqual(formula_to_lean(Var("A")), "A")

    def test_not(self):
        self.assertEqual(formula_to_lean(Not(Var("A"))), "(¬A)")

    def test_implies(self):
        self.assertEqual(formula_to_lean(Implies(Var("A"), Var("B"))), "(A → B)")

    def test_and(self):
        self.assertEqual(formula_to_lean(And(Var("A"), Var("B"))), "(A ∧ B)")

    def test_or(self):
        self.assertEqual(formula_to_lean(Or(Var("A"), Var("B"))), "(A ∨ B)")

    def test_iff(self):
        self.assertEqual(formula_to_lean(Iff(Var("A"), Var("B"))), "(A ↔ B)")

    def test_forall(self):
        self.assertEqual(formula_to_lean(Forall("x", Pred("P", [Var("x")]))), "(∀ x, (P x))")

    def test_exists(self):
        self.assertEqual(formula_to_lean(Exists("x", Pred("P", [Var("x")]))), "(∃ x, (P x))")

    def test_equals(self):
        self.assertEqual(formula_to_lean(Equals(Var("x"), Var("y"))), "(x = y)")

    def test_pred(self):
        self.assertEqual(formula_to_lean(Pred("P", [])), "P")
        self.assertEqual(formula_to_lean(Pred("P", [Var("x"), "y"])), "(P x y)")

    def test_unknown_object(self):
        self.assertEqual(formula_to_lean(123), "123")


class TestExportProof(unittest.TestCase):
    def setUp(self):
        self.temp_db_file = tempfile.NamedTemporaryFile(delete=False, suffix=".db")
        self.temp_db_file.close()
        self.db = TheoryDatabase(db_path=self.temp_db_file.name)

    def tearDown(self):
        if os.path.exists(self.temp_db_file.name):
            os.remove(self.temp_db_file.name)

    def test_export_proof_nonexistent_theorem(self):
        with self.assertRaises(ValueError) as ctx:
            export_proof("nonexistent", self.db)
        self.assertIn("Theorem 'nonexistent' not found", str(ctx.exception))

    def test_export_proof_basic(self):
        steps = [
            {
                'step_idx': 0,
                'formula_str': 'A -> A',
                'justification_type': 'Hypothesis',
                'arg1': None,
                'arg2': None,
                'ref_name': 'h0',
                'substitution_json': None
            }
        ]
        self.db.save_theorem(
            name="identity",
            thesis_str="A -> A",
            hypotheses=["A -> A"],
            steps=steps,
            is_verified=1
        )

        lean_code = export_proof("identity", self.db)
        self.assertIn("-- Auto-generated by solver.lean_exporter", lean_code)
        self.assertIn("variable (A : Prop)", lean_code)
        self.assertIn("theorem identity (h0 : (A → A)) : (A → A) := by", lean_code)
        self.assertIn("have step_0 : (A → A) := h0", lean_code)
        self.assertIn("exact step_0", lean_code)

    def test_export_proof_with_axiom_and_mp(self):
        self.db.add_axiom("ax1", "A -> (B -> A)")

        steps = [
            {
                'step_idx': 0,
                'formula_str': 'A',
                'justification_type': 'Hypothesis',
                'arg1': None,
                'arg2': None,
                'ref_name': 'h0',
                'substitution_json': None
            },
            {
                'step_idx': 1,
                'formula_str': 'A -> (B -> A)',
                'justification_type': 'Axiom',
                'arg1': None,
                'arg2': None,
                'ref_name': 'ax1',
                'substitution_json': {'A': 'A', 'B': 'B'}
            },
            {
                'step_idx': 2,
                'formula_str': 'B -> A',
                'justification_type': 'MP',
                'arg1': 1,
                'arg2': 0,
                'ref_name': None,
                'substitution_json': None
            }
        ]
        self.db.save_theorem(
            name="thm_mp",
            thesis_str="B -> A",
            hypotheses=["A"],
            steps=steps,
            is_verified=1
        )

        lean_code = export_proof("thm_mp", self.db)
        self.assertIn("variable (A B : Prop)", lean_code)
        self.assertIn("axiom ax1 (A B : Prop) : (A → (B → A))", lean_code)
        self.assertIn("theorem thm_mp (h0 : A) : (B → A) := by", lean_code)
        self.assertIn("have step_0 : A := h0", lean_code)
        self.assertIn("have step_1 : (A → (B → A)) := ax1 A B", lean_code)
        self.assertIn("have step_2 : (B → A) := step_1 step_0", lean_code)
        self.assertIn("exact step_2", lean_code)

    def test_export_proof_axiom_without_free_vars(self):
        # Axiom with closed formula (no free variables)
        self.db.add_axiom("ax_forall", "forall x, P(x)")

        steps = [
            {
                'step_idx': 0,
                'formula_str': 'forall x, P(x)',
                'justification_type': 'Axiom',
                'arg1': None,
                'arg2': None,
                'ref_name': 'ax_forall',
                'substitution_json': None
            }
        ]
        self.db.save_theorem(
            name="thm_ax_closed",
            thesis_str="forall x, P(x)",
            hypotheses=[],
            steps=steps,
            is_verified=1
        )

        lean_code = export_proof("thm_ax_closed", self.db)
        self.assertIn("axiom ax_forall : (∀ x, (P x))", lean_code)
        self.assertIn("have step_0 : (∀ x, (P x)) := ax_forall", lean_code)

    def test_export_proof_axiom_without_substitution_json(self):
        self.db.add_axiom("ax1", "A -> (B -> A)")

        steps = [
            {
                'step_idx': 0,
                'formula_str': 'X -> (Y -> X)',
                'justification_type': 'Axiom',
                'arg1': None,
                'arg2': None,
                'ref_name': 'ax1',
                'substitution_json': None
            }
        ]
        self.db.save_theorem(
            name="thm_ax_nosub",
            thesis_str="X -> (Y -> X)",
            hypotheses=[],
            steps=steps,
            is_verified=1
        )

        lean_code = export_proof("thm_ax_nosub", self.db)
        self.assertIn("have step_0 : (X → (Y → X)) := ax1 X Y", lean_code)

    def test_export_proof_mp_reverse_args(self):
        steps = [
            {
                'step_idx': 0,
                'formula_str': 'A -> B',
                'justification_type': 'Hypothesis',
                'arg1': None,
                'arg2': None,
                'ref_name': 'h0',
                'substitution_json': None
            },
            {
                'step_idx': 1,
                'formula_str': 'A',
                'justification_type': 'Hypothesis',
                'arg1': None,
                'arg2': None,
                'ref_name': 'h1',
                'substitution_json': None
            },
            {
                'step_idx': 2,
                'formula_str': 'B',
                'justification_type': 'MP',
                'arg1': 1,  # antecedent
                'arg2': 0,  # implication
                'ref_name': None,
                'substitution_json': None
            }
        ]
        self.db.save_theorem(
            name="thm_mp_rev",
            thesis_str="B",
            hypotheses=["A -> B", "A"],
            steps=steps,
            is_verified=1
        )

        lean_code = export_proof("thm_mp_rev", self.db)
        self.assertIn("have step_2 : B := step_0 step_1", lean_code)

    def test_export_proof_with_lemma_dependency(self):
        base_steps = [
            {
                'step_idx': 0,
                'formula_str': 'A',
                'justification_type': 'Hypothesis',
                'arg1': None,
                'arg2': None,
                'ref_name': 'h0',
                'substitution_json': None
            }
        ]
        self.db.save_theorem(
            name="base_thm",
            thesis_str="A",
            hypotheses=["A"],
            steps=base_steps,
            is_verified=1
        )

        dep_steps = [
            {
                'step_idx': 0,
                'formula_str': 'B',
                'justification_type': 'Hypothesis',
                'arg1': None,
                'arg2': None,
                'ref_name': 'h0',
                'substitution_json': None
            },
            {
                'step_idx': 1,
                'formula_str': 'B',
                'justification_type': 'Lemma',
                'arg1': 0,
                'arg2': None,
                'ref_name': 'base_thm',
                'substitution_json': {'A': 'B'}
            }
        ]
        self.db.save_theorem(
            name="main_thm",
            thesis_str="B",
            hypotheses=["B"],
            steps=dep_steps,
            dependencies=["base_thm"],
            is_verified=1
        )

        lean_code = export_proof("main_thm", self.db)
        self.assertIn("axiom base_thm (A : Prop) (h0 : A) : A", lean_code)
        self.assertIn("have step_1 : B := base_thm B step_0", lean_code)

    def test_export_proof_lemma_without_substitution_json(self):
        base_steps = [
            {
                'step_idx': 0,
                'formula_str': 'A',
                'justification_type': 'Hypothesis',
                'arg1': None,
                'arg2': None,
                'ref_name': 'h0',
                'substitution_json': None
            }
        ]
        self.db.save_theorem(
            name="base_thm",
            thesis_str="A",
            hypotheses=["A"],
            steps=base_steps,
            is_verified=1
        )

        dep_steps = [
            {
                'step_idx': 0,
                'formula_str': 'C',
                'justification_type': 'Hypothesis',
                'arg1': None,
                'arg2': None,
                'ref_name': 'h0',
                'substitution_json': None
            },
            {
                'step_idx': 1,
                'formula_str': 'C',
                'justification_type': 'Lemma',
                'arg1': 0,
                'arg2': None,
                'ref_name': 'base_thm',
                'substitution_json': None
            }
        ]
        self.db.save_theorem(
            name="main_thm_nosub",
            thesis_str="C",
            hypotheses=["C"],
            steps=dep_steps,
            dependencies=["base_thm"],
            is_verified=1
        )

        lean_code = export_proof("main_thm_nosub", self.db)
        self.assertIn("have step_1 : C := base_thm C step_0", lean_code)

    def test_export_proof_unknown_justification(self):
        mock_thm = {
            'id': 1,
            'name': 'thm_unknown',
            'thesis_str': 'A',
            'lean_code': None,
            'is_verified': 0,
            'hypotheses': [],
            'steps': [
                {
                    'step_idx': 0,
                    'formula_str': 'A',
                    'justification_type': 'CustomType',
                    'arg1': None,
                    'arg2': None,
                    'ref_name': None,
                    'substitution_json': None
                }
            ]
        }
        with patch.object(self.db, 'get_theorem', return_value=mock_thm):
            lean_code = export_proof("thm_unknown", self.db)
            self.assertIn("have step_0 : A := sorry", lean_code)


if __name__ == "__main__":
    unittest.main()
