"""
Lean 4 Exporter Module
======================
Translates Python Formula ASTs into Lean 4 formal logic syntax and exports
self-contained Lean 4 proof files for verification.
"""

from .formula import (
    Formula, Var, Not, Implies, And, Or, Iff,
    Forall, Exists, Equals, Pred, parse_formula
)
from .database import TheoryDatabase


def formula_to_lean(formula: Formula) -> str:
    """
    Recursively maps a Formula AST node into the corresponding Lean 4 syntax string.
    """
    if isinstance(formula, Var):
        return formula.name
    elif isinstance(formula, Not):
        return f"(¬{formula_to_lean(formula.formula)})"
    elif isinstance(formula, Implies):
        return f"({formula_to_lean(formula.left)} → {formula_to_lean(formula.right)})"
    elif isinstance(formula, And):
        return f"({formula_to_lean(formula.left)} ∧ {formula_to_lean(formula.right)})"
    elif isinstance(formula, Or):
        return f"({formula_to_lean(formula.left)} ∨ {formula_to_lean(formula.right)})"
    elif isinstance(formula, Iff):
        return f"({formula_to_lean(formula.left)} ↔ {formula_to_lean(formula.right)})"
    elif isinstance(formula, Forall):
        return f"(∀ {formula.var}, {formula_to_lean(formula.body)})"
    elif isinstance(formula, Exists):
        return f"(∃ {formula.var}, {formula_to_lean(formula.body)})"
    elif isinstance(formula, Equals):
        return f"({formula_to_lean(formula.left)} = {formula_to_lean(formula.right)})"
    elif isinstance(formula, Pred):
        if formula.args:
            args_str = " ".join(
                formula_to_lean(a) if isinstance(a, Formula) else str(a)
                for a in formula.args
            )
            return f"({formula.name} {args_str})"
        return formula.name
    else:
        return str(formula)


def export_proof(theorem_name: str, db: TheoryDatabase) -> str:
    """
    Loads a theorem and its dependency graph from the database and generates
    a complete, self-contained Lean 4 source document.
    """
    thm = db.get_theorem(theorem_name)
    if not thm:
        raise ValueError(f"Theorem '{theorem_name}' not found in database.")

    dep_names = db.get_dependencies_recursive(theorem_name)
    dep_thms = [db.get_theorem(name) for name in dep_names if db.get_theorem(name)]

    # 1. Collect all referenced axioms
    axiom_names = []
    for step in thm['steps']:
        if step['justification_type'] == 'Axiom':
            ax_name = step['ref_name']
            if ax_name and ax_name not in axiom_names:
                axiom_names.append(ax_name)

    # 2. Collect free variables for global variable declarations
    collected_vars = set()

    thesis_f = parse_formula(thm['thesis_str'])
    collected_vars.update(thesis_f.free_variables())

    hyps_f = [parse_formula(h) for h in thm['hypotheses']]
    for h in hyps_f:
        collected_vars.update(h.free_variables())

    for step in thm['steps']:
        step_f = parse_formula(step['formula_str'])
        collected_vars.update(step_f.free_variables())

    for d_thm in dep_thms:
        d_thesis = parse_formula(d_thm['thesis_str'])
        collected_vars.update(d_thesis.free_variables())
        for h_str in d_thm['hypotheses']:
            collected_vars.update(parse_formula(h_str).free_variables())

    prop_vars = sorted(list(collected_vars))

    lines = ["-- Auto-generated by solver.lean_exporter", ""]

    if prop_vars:
        lines.append(f"variable ({' '.join(prop_vars)} : Prop)")
        lines.append("")

    # 3. Declare Axioms
    if axiom_names:
        for ax_name in axiom_names:
            ax_str = db.get_axiom(ax_name)
            if ax_str:
                ax_f = parse_formula(ax_str)
                ax_vars = sorted(list(ax_f.free_variables()))
                if ax_vars:
                    lines.append(
                        f"axiom {ax_name} ({' '.join(ax_vars)} : Prop) : {formula_to_lean(ax_f)}"
                    )
                else:
                    lines.append(f"axiom {ax_name} : {formula_to_lean(ax_f)}")
        lines.append("")

    # 4. Declare Prerequisite Lemma Axioms
    if dep_thms:
        for dep_thm in dep_thms:
            l_name = dep_thm['name']
            l_thesis = parse_formula(dep_thm['thesis_str'])
            l_hyps = [parse_formula(h) for h in dep_thm['hypotheses']]

            l_vars = set(l_thesis.free_variables())
            for lh in l_hyps:
                l_vars.update(lh.free_variables())
            sorted_lvars = sorted(list(l_vars))

            hyp_decls = [
                f"(h{idx} : {formula_to_lean(h)})"
                for idx, h in enumerate(l_hyps)
            ]

            param_parts = []
            if sorted_lvars:
                param_parts.append(f"({' '.join(sorted_lvars)} : Prop)")
            if hyp_decls:
                param_parts.extend(hyp_decls)

            param_str = (" " + " ".join(param_parts)) if param_parts else ""
            lines.append(
                f"axiom {l_name}{param_str} : {formula_to_lean(l_thesis)}"
            )
        lines.append("")

    # 5. Declare Main Theorem Signature
    hyp_params = [
        f"(h{idx} : {formula_to_lean(h)})"
        for idx, h in enumerate(hyps_f)
    ]
    param_str = (" " + " ".join(hyp_params)) if hyp_params else ""
    lines.append(
        f"theorem {thm['name']}{param_str} : {formula_to_lean(thesis_f)} := by"
    )

    # 6. Generate Proof Steps
    step_formulas = {
        s['step_idx']: parse_formula(s['formula_str'])
        for s in thm['steps']
    }

    for step in thm['steps']:
        idx = step['step_idx']
        f = step_formulas[idx]
        f_lean = formula_to_lean(f)
        j_type = step['justification_type']

        if j_type == 'Axiom':
            ax_name = step['ref_name']
            ax_str = db.get_axiom(ax_name)
            if ax_str:
                ax_f = parse_formula(ax_str)
                while isinstance(ax_f, Forall):
                    ax_f = ax_f.body
                ax_vars = sorted(list(ax_f.free_variables()))
                if ax_vars:
                    sub_json = step.get('substitution_json')
                    if not sub_json:
                        bindings = f.match_schema(ax_f)
                        sub_json = (
                            {k: str(v) for k, v in bindings.items()}
                            if bindings else {}
                        )

                    args = []
                    for v in ax_vars:
                        if v in sub_json:
                            val = sub_json[v]
                            val_f = parse_formula(val) if isinstance(val, str) else val
                            args.append(formula_to_lean(val_f))
                    term = f"{ax_name} {' '.join(args)}" if args else ax_name
                else:
                    term = ax_name
            else:
                term = ax_name

        elif j_type == 'Hypothesis':
            term = step['ref_name']

        elif j_type == 'MP':
            arg1 = step['arg1']
            arg2 = step['arg2']
            f1 = step_formulas[arg1]
            f2 = step_formulas[arg2]

            if isinstance(f1, Implies) and f1.left == f2:
                impl_idx, ant_idx = arg1, arg2
            elif isinstance(f2, Implies) and f2.left == f1:
                impl_idx, ant_idx = arg2, arg1
            else:
                impl_idx, ant_idx = arg1, arg2

            term = f"step_{impl_idx} step_{ant_idx}"

        elif j_type == 'Lemma':
            l_name = step['ref_name']
            l_thm = db.get_theorem(l_name)
            if l_thm:
                l_thesis = parse_formula(l_thm['thesis_str'])
                l_hyps = [parse_formula(h) for h in l_thm['hypotheses']]

                l_vars = set(l_thesis.free_variables())
                for lh in l_hyps:
                    l_vars.update(lh.free_variables())
                sorted_lvars = sorted(list(l_vars))

                sub_json = step.get('substitution_json')
                if not sub_json:
                    bindings = f.match_schema(l_thesis)
                    sub_json = (
                        {k: str(v) for k, v in bindings.items()}
                        if bindings else {}
                    )

                var_args = []
                for v in sorted_lvars:
                    if v in sub_json:
                        val = sub_json[v]
                        val_f = parse_formula(val) if isinstance(val, str) else val
                        var_args.append(formula_to_lean(val_f))

                hyp_args = []
                if len(l_hyps) >= 1 and step.get('arg1') is not None:
                    hyp_args.append(f"step_{step['arg1']}")
                if len(l_hyps) >= 2 and step.get('arg2') is not None:
                    hyp_args.append(f"step_{step['arg2']}")

                all_args = var_args + hyp_args
                term = f"{l_name} {' '.join(all_args)}" if all_args else l_name
            else:
                term = l_name
        else:
            term = "sorry"

        lines.append(f"  have step_{idx} : {f_lean} := {term}")

    last_idx = thm['steps'][-1]['step_idx']
    lines.append(f"  exact step_{last_idx}")

    return "\n".join(lines) + "\n"
